class DataFiles {
  // types of sign
  //1. Mandatory signs
  //2. Prohibitory signs
  //3. informational  signs
  static Map<String, String> mandatorySigns = {
    'assets/signs/1.png': 'रोक्न निषेध',
    'assets/signs/2.png': 'पार्किंग निषेध',
    'assets/signs/3.png': 'प्रवेश निषेध',
    'assets/signs/4.png': 'दाहिने मोड्न निषेध',
    'assets/signs/5.png': 'बायाँ मोड्न निषेध',
    'assets/signs/6.png': 'यु टर्न निषेध',
    'assets/signs/7.png': 'अधिकतम गति',
    'assets/signs/8.png': 'सवारी चौडाई सिमा',
    'assets/signs/9.png': 'उछिन्न निषेध',
    'assets/signs/10.png': 'हर्न निषेध',
    'assets/signs/11.png': 'रोक हेर र जाउ',
    'assets/signs/12.png': 'गति सिमा समाप्त',
    'assets/signs/13.png': 'सिधा मात्र',
    'assets/signs/14.png': 'आगाडी गएर बायाँ मोड',
    'assets/signs/15.png': 'कुनै तिर बाट जाउ',
    'assets/signs/16.png': 'सानो गोल घुम्ती',
    'assets/signs/17.png': 'सवारी भार सिमा',
    'assets/signs/18.png': 'बायाँ मोड',
    'assets/signs/19.png': 'बायाँ च्याप',
    'assets/signs/20.png': 'एकतर्फी सवारी',
    'assets/signs/21.png': 'रोक र जनदेउ',
    'assets/signs/22.png': 'मूल सडक या गोलघुम्तीमा आउनेलाई पहिला जन देउ',
    'assets/signs/23.png': 'ट्रक निषेध',
    'assets/signs/24.png': 'सवारी लम्बाई सिमा',
    'assets/signs/25.png': 'सवारी उचाई सिमा',
    'assets/signs/26.png': 'एक्सल भार सिमा',
    'assets/signs/27.png': 'पैदल यात्री निषेध',
    'assets/signs/28.png': 'बेलगाडा निषेध',
    'assets/signs/29.png': 'गति सिमा समाप्त',
    'assets/signs/30.png': 'जाउ',
  };
  static Map<String, String> warningSigns = {
    // warning signs
    'assets/signs/31.png': 'T जन्क्सन',
    'assets/signs/32.png': 'खतरा',
    'assets/signs/33.png': 'आगाडी दुइतर्फी सिधा बाटो',
    'assets/signs/34.png': 'आगाडी दुइतर्फी बाटो',
    'assets/signs/35.png': 'दाहिने मोड',
    'assets/signs/36.png': 'दाहिने मोड पुरा',
    'assets/signs/37.png': 'साँघुरो पुल',
    'assets/signs/38.png': 'बढी उकालो',
    'assets/signs/39.png': 'खातारनाख दबेको बाटो',
    'assets/signs/40.png': 'दुबैतिर बाट साँघुरिएको बाटो',
    'assets/signs/41.png': 'पहिरो झर्ने ठाउँ',
    'assets/signs/42.png': 'दाहिनेबाट साँघुरो बाटो',
    'assets/signs/43.png': 'दोहोरो मोड',
    'assets/signs/44.png': 'वाई Y जन्क्सन ',
    'assets/signs/45.png': 'बायाँ बाट सवारी आउन सक्छ',
    'assets/signs/46.png': 'दाहिनेबाट सवारी आउन सक्छ',
    'assets/signs/47.png': 'गोल घुम्ती',
    'assets/signs/48.png': 'आगाडी उचाई सिमा',
    'assets/signs/49.png': 'चौबाटो आगाडी सडक',
    'assets/signs/50.png': 'चौबाटो आगाडी शाखा सडक',
    'assets/signs/51.png': 'बढी ओरालो',
    'assets/signs/52.png': 'पाल्तु जनावर',
    'assets/signs/53.png': 'कम उचाईमा डिलहरु',
    'assets/signs/54.png': 'उठेको बाटो',
    'assets/signs/55.png': 'पैदल यात्रीले बाटो काट्ने ठाउँ',
    'assets/signs/56.png': 'दाहिने सडक शाखा',
    'assets/signs/57.png': 'एकपछि अर्को दोबाटोहरु',
    'assets/signs/58.png': 'दोहोरो बाटो समाप्त',
    'assets/signs/59.png': 'ट्राफिक चिन्ह',
    'assets/signs/60.png': 'जंगली जनावर',
    'assets/signs/61.png': 'पैदल यात्री',
    'assets/signs/62.png': 'नदीको किनारा',
    'assets/signs/63.png': 'रेल गाडी गेट नभएको',
    'assets/signs/64.png': 'गिट्टी उच्छिटीन सक्ने',
    'assets/signs/65.png': 'बाटोमा काम हुदै',
    'assets/signs/66.png': 'जाच चौकी',
    'assets/signs/67.png': 'केटाकेटीहरु',
    'assets/signs/68.png': 'बायाँतिर तिखो मोड',
    'assets/signs/69.png': 'चाल्न तिखो मोड (अस्थाई बाटो)',
    'assets/signs/70.png': 'टि T जंक्सन',
  };
  static Map<String, String> infoSign = {
    // information signs
    'assets/signs/71.png': 'पार्किंग स्थल',
    'assets/signs/72.png': 'एकतर्फी बाटो',
    'assets/signs/73.png': 'वर्कशप',
    'assets/signs/74.png': 'प्राथमिक उपचार चौकी',
    'assets/signs/75.png': 'उछिन्ने ठाउँ',
    'assets/signs/76.png': 'टेलिफोन',
    'assets/signs/77.png': 'बाटो अन्त',
    'assets/signs/78.png': 'पैदल यात्रीको बाटो',
    'assets/signs/79.png': 'पेट्रोल पम्प',
    'assets/signs/80.png': 'बास बस्ने ठाउँ',
    'assets/signs/81.png': 'अस्पताल',
    'assets/signs/82.png': 'जलपान ठाउ',
    'assets/signs/83.png': 'पैदल यात्री र साइकल को बाटो ',
    'assets/signs/84.png': 'रेस्टुरा',
    'assets/signs/85.png': 'पैदल यात्रीको बाटो',
    'assets/signs/86.png': 'साइकल को बाटो',
    'assets/signs/87.png': 'बस बिसौनी',
    'assets/signs/88.png': 'बनभोज क्षेत्र',
    'assets/signs/89.png': 'जेब्रा क्रसिङ',
    'assets/signs/90.png': 'अत्यन्त जरुरि भए मात्र राख्न',
    'assets/signs/91.png': 'सडक छेउ का रेखाहरु',
    'assets/signs/92.png': 'सडक बिचका रेखाहरु',
  };
}
